#!/bin/bash

qemu-system-x86_64 -machine q35,accel=tcg -smp cpus=8  \
  -kernel out/x64/arch/x86/boot/bzImage \
  -append "console=ttyS0 root=/dev/sda earlyprintk=serial nokaslr"\
  -net user,hostfwd=tcp::10021-:22 -net nic \
  -nographic -serial mon:stdio \
  -m 16G \
  -s -S \
  -pidfile vm.pid \
  2>&1 | tee vm.log

  # -hda image/bullseye.img \

  echo "QEMU was started."